webhookVersion: 104.0.0+up0.5.0-rc8
provisioningCAPIVersion: 104.0.0+up0.2.0
cspAdapterMinVersion: 104.0.0+up4.0.0-rc1
defaultShellVersion: rancher/shell:v0.2.1-rc.2
fleetVersion: 104.0.0+up0.10.0-rc.14
