name: build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x]
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go-version }}

      - run: curl.exe -sfL https://releases.rancher.com/dapper/latest/dapper-Windows-x86_64.exe -o dapper.exe
      - run: ./dapper.exe -f Dockerfile-windows.dapper -d quickbuild
