name: build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  compatibility:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.20.x]
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Setup Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: ${{ matrix.go-version }}

      # Break-down each step in make ci, so that they can be retried independently.
      - run: make validate
      - run: make quick # build and package
      - run: make test
      - run: make chart/ci
